#!/bin/bash
# /home/pi/433mhz_decoder/433Utils/RPi_utils

### BEGIN INIT INFO
# Provides:          servoblaster
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in 
    start)
        echo "Starting RFSniffer"
        /home/pi/433mhz_decoder/433Utils/RPi_utils/RFSniffer &
        ;;
    stop)
        echo "Stopping RFSniffer"
        killall RFSniffer
        ;;
    *)
        echo "Usage: /etc/init.dRFSniffer start|stop"
        exit 1
        ;;
esac

exit 0
